# Generated by Django 3.2.7 on 2021-09-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskstate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
