# Generated by Django 3.2.7 on 2021-09-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskstate', '0003_task_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
